---
title: "本地BLAST的安装与使用"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 学习要求

* 操作系统为 Linux (Ubuntu或类似版本)，或 MacOS
* 具有Linux系统操作基础

## 1. 下载并安装BLAST

### 1.1 Ubuntu 安装

在Ubuntu的 terminal 中运行：

```{sh eval=F}
blastp
```

如果出现：

```{sh eval=F}
Command 'blastp' not found, but can be installed with:

apt install ncbi-blast+
```

则表示还未安装，可以按提示的命令进行安装：

```{sh eval=F}
sudo apt install ncbi-blast+
```

**注意** 安装需要 ```root``` 或超级用户权限。

如果出现：

```{sh eval=F}
BLAST query/options error: Either a BLAST database or subject sequence(s) must be specified
Please refer to the BLAST+ user manual.
```

则表示已经安装过了。


### 1.2 MacOS 安装

* 在浏览器中输入： ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/，进入NCBI BLAST的FTP下载页面。

* 然后选择合适的版本进行下载，文件名通常为： ```ncbi-blast-#####+-x64-macosx.tar.gz ```。其中 ```#####``` 为版本号，比如：```2.9.0```。

* 解压缩后，进入 terminal ，用以下命令将相关可执行文件 ``` copy ``` 到 ``` /usr/local/bin ``` 目录：

```{sh eval=F}
cp /path/to/NCBI_blast_folder/bin/* /usr/local/bin
```

其中 ``` /path/to/NCBI_blast_folder ``` 为解压缩后产生的目录，比如： ``` /Users/wchen/Downloads/ncbi-blast-2.9.0+ ```。

* 之后在terminal的任何目录下运行：

```{sh eval=F}
blastp -h
```

如果出现 ```blastp USAGE``` 信息，即为安装成功。

## 2. 准备数据库及索引文件

下面以小鼠所有的```protein coding genes``` (蛋白序列) 为数据库。

* 从浏览器进入： ftp://ftp.ncbi.nlm.nih.gov/refseq/M_musculus/mRNA_Prot/

* 下载 ``` mouse.1.protein.faa.gz ```

* 解压缩后，得到 ``` mouse.1.protein.faa ``` 

* 从 ``` terminal ``` 程序进入 ``` mouse.1.protein.faa ```  所在的目录

* 运行以下命令建立索引：

```{sh eval=F}
makeblastdb -in mouse.1.protein.faa -dbtype prot
```

``` makeblastdb ``` 建立索引程序，它两个参数的意义为：

* ``` -in ``` ： 输入文件， ``` fasta ``` 格式

* ``` -dbtype ``` ：序列类型； ``` prot ``` 表示蛋白序列， ``` nucl ``` 表示核酸

可使用 ``` makeblastdb -help ``` 命令查看其它参数及使用方法。

运行成功后，会得到以下几个文件：

```{sh eval=F}
mouse.1.protein.faa.phr
mouse.1.protein.faa.psq
mouse.1.protein.faa.pin
```


## 3. 准备 ``` query ``` 序列

我们从NCBI搜索并下载 ``` brca1 ``` 基因的蛋白序列，作为 ``` query ``` 序列。``` query ``` 文件可以包含多个序列。

* 从浏览器进入NCBI蛋白质数据库： https://www.ncbi.nlm.nih.gov/protein/

* 在搜索框内输入： ``` human[organism] brca1 ``` 

* 选择第一个搜索结果，即：https://www.ncbi.nlm.nih.gov/protein/AAC37594.1

* 下载其 ``` fasta ``` 格式序列，保存到 ``` mouse.1.protein.faa ```  所在的目录，取名为： ``` human_brca1.faa ``` 。

* 用 ``` more human_brca1.faa ``` 查看文件内容，确认其格式正确。

## 4. 运行 ``` blast ``` 并查看结果

用以下命令进行 ``` blast ``` ，将 ``` human brca1 ``` 的蛋白序列与所有小鼠蛋白序列进行比较：

```{sh eval=F} 
blastp -query human_brca1.faa \
    -db mouse.1.protein.faa \
    -out hm_brca1_blp_mm_GRCm38.out.txt \
    -evalue 1e-5
```

上述参数分别为：

```{sh eval=F}
-query  : 输入序列文件
-db     : 数据库文件
-out    : 比对输出结果文件
-evalue : e-value cutoff 值
```

其它参数可通过 ``` blastp -help ``` 查看。

注意：``` blast ``` 结果可以有**19种**输出格式，用 ``` -outfmt ``` 参数指定，取值范围为 ``` 0-18 ``` 。其中 ``` 0, 6, 7 ``` 最为常用。

比如，指定输出格式为**7** (Tabular with comment lines)：

```{sh eval=F} 
blastp -query human_brca1.faa \
    -db mouse.1.protein.faa \
    -out hm_brca1_blp_mm_GRCm38.outfmt7.txt \
    -outfmt 7 \
    -evalue 1e-5
```

请自行查看结果 (```hm_brca1_blp_mm_GRCm38.outfmt7.txt```) 并比较与默认输出 (```hm_brca1_blp_mm_GRCm38.out.txt```) 的区别。
